name: soltoon
containers:
  client-java:
    name: soltoon-client:0.1
    resources:
      memory: 50000000
      cpu: 1
      timeout: 300
  server:
    name: soltoon-server:0.1
    resources:
      memory: 50000000
      cpu: 1
      timeout: 100